name = "VGDLGym"
uuid = "9e305de2-99bb-4afa-be74-5afaf0d0dbe6"
authors = ["belledon <mbelledonne@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
